services:
  mysql:
    image: mysql:8.0
    container_name: my_exam_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123!
      MYSQL_DATABASE: examemwork_db
      MYSQL_USER: examemwork
      MYSQL_PASSWORD: examemwork
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
